In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Load the cleaned data (not raw!)
df = pd.read_csv("03_preprocessing .csv")
df.head()

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_Germany,Geography_Spain,Gender_Male
0,619,42,2,0.00,1,1,1,101348.88,1,False,False,False
1,608,41,1,83807.86,1,0,1,112542.58,0,False,True,False
2,502,42,8,159660.80,3,1,0,113931.57,1,False,False,False
3,699,39,1,0.00,2,0,0,93826.63,0,False,False,False
4,850,43,2,125510.82,1,1,1,79084.10,0,False,True,False

In [2]:
# How much of their salary do they keep in bank?
df["BalanceToSalary"] = (df["Balance"]) / (df["EstimatedSalary"] + 1)

# +1 avoids division by zero
# High ratio = keeps more money in bank = more invested?
df["BalanceToSalary"].head()

0    0.000000
1    0.744670
2    1.401362
3    0.000000
4    1.587035
Name: BalanceToSalary, dtype: float64

In [3]:
# Are they using many products relative to how long they've been here?
df["ProductsPerYear"] = df["NumOfProducts"] / (df["Tenure"] + 1)

# +1 avoids division by zero for new customers

df["ProductsPerYear"].head()

0    0.333333
1    0.500000
2    0.333333
3    1.000000
4    0.333333
Name: ProductsPerYear, dtype: float64

In [4]:
# Active member with more products = truly engaged?
df["EngagementScore"] = df["IsActiveMember"] * df["NumOfProducts"]

# Active + 2 products = score of 2
# Inactive + 2 products = score of 0
df["EngagementScore"].head()

0    1
1    1
2    0
3    0
4    1
Name: EngagementScore, dtype: int64

In [5]:
# How old were they when they joined?
df["AgeWhenJoined"] = df["Age"] - df["Tenure"]

# Older customer who just joined is very different
# from young customer who joined young and stayed

df["AgeWhenJoined"].head()

0    40
1    40
2    34
3    38
4    41
Name: AgeWhenJoined, dtype: int64

In [6]:
df.head()

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_Germany,Geography_Spain,Gender_Male,BalanceToSalary,ProductsPerYear,EngagementScore,AgeWhenJoined
0,619,42,2,0.00,1,1,1,101348.88,1,False,False,False,0.000000,0.333333,1,40
1,608,41,1,83807.86,1,0,1,112542.58,0,False,True,False,0.744670,0.500000,1,40
2,502,42,8,159660.80,3,1,0,113931.57,1,False,False,False,1.401362,0.333333,0,34
3,699,39,1,0.00,2,0,0,93826.63,0,False,False,False,0.000000,1.000000,0,38
4,850,43,2,125510.82,1,1,1,79084.10,0,False,True,False,1.587035,0.333333,1,41

In [8]:
# Save cleaned dataframe as CSV
df.to_csv("04_Featureengg .csv", index=False)
print("Saved successfully!")

Saved successfully!